### ISSUE TITLE
Value Error:could not convert string to float: b'**'

### ISSUE THREAD

**Issue by sgiangola** [olemb/dbfread#10]
DBF file contains a value of '0.00**' in an int field, when I go to read I get the following error. I understand that the problem is in part due to data impurity in the DBF files I am using, but thought you'd like to be aware of the issue.

  File "C:\Continuum\Anaconda3\lib\site-packages\dbfread\dbf.py", line 310, in _iter_records
    for field in self.fields]
  File "C:\Continuum\Anaconda3\lib\site-packages\dbfread\dbf.py", line 310, in <listcomp>
    for field in self.fields]
  File "C:\Continuum\Anaconda3\lib\site-packages\dbfread\field_parser.py", line 75, in parse
    return func(field, data)
  File "C:\Continuum\Anaconda3\lib\site-packages\dbfread\field_parser.py", line 164, in parseN
    return float(data.replace(b',', b'.'))
ValueError: could not convert string to float: b'**'

**Comment by olemb** [comment]
It looks like there are two '\*' characters at the end of each value. I first thought it might be padding, but '0.00\*\*' and '\*\*' are not the same length.

Could you try to open the file with raw=True and see what you get?

Here's a workaround that might work:

    from dbfread import DBF, FieldParser

    class AsteriskFieldParser(FieldParser):
        def parseN(self, field, value):
            value = value.strip().strip('*')
            return FieldParser.parseN(self, field, value)

    f = DBF('test.dbf', load=True, encoding='latin1',
            parserclass=AsteriskFieldParser)

**Comment by sgiangola** [comment]
Thanks for the help. My work around was editing the parseN function in field_parser. I added another replace() to account for the asterisks and replaced them with a 0, resulting in '0.000'. I also tried to replace the majority of the "0.00\*\*" values in the actual dbf files. I realize this could cause problems if a value of "5\*\*", for example, showed up but it appears to have been OK in my use case. 

    def parseN(self, field, data):
        """Parse numeric field (N)

        Returns int, float or None if the field is empty.
        """
        try:
            return int(data)
        except ValueError:
            if not data.strip():
                return None
            else:
                # Account for , in numeric fields
                return float(data.replace(b',', b'.').replace(b'**', b'0'))

**Comment by olemb** [comment]
Why not simply remove the '*' characters? 0.000 is the same as 0.00 after all.

**Comment by Matungos** [comment]
I'm having this error:
in parseN
    return float(data.replace(b',', b'.'))
ValueError: could not convert string to float: b'***********'

**Comment by olemb** [comment]
I've added some code to remove the '*' characters in float fields. Could you try my develop branch and see if it works for you?

**Comment by Matungos** [comment]
In develop branch but adding the same line to parseN too works fine.
In my case the column with problems is a numeric field.

**Comment by olemb** [comment]
Ah, sounds good. I've pushed a fix to my develop branch. Thanks for reporting this.

**Comment by chriskuipers** [comment]
Had the same problem, but with an tailing . (dot). Modified parseN to also do a rsplit(b'.'). Works like a charm! Thanks
