### ISSUE TITLE
UnicodeDecodeError error

### ISSUE THREAD

**Issue by ccfiel** [olemb/dbfread#13]
Hello Guys,

I got this error

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xab in position 16: ordinal not in range(128)

```
    from dbfread import DBF
    for item in DBF('/home/chris/Desktop/ITEM.DBF'):
        print item
```

I tried to put encoding 
```
    from dbfread import DBF
    for item in DBF('/home/chris/Desktop/ITEM.DBF', encoding='utf-8'):
        print item
```
Still get this error

```
  File "/home/chris/frappe-bench/env/local/lib/python2.7/site-packages/dbfread/dbf.py", line 304, in _iter_records
    for field in self.fields]
  File "/home/chris/frappe-bench/env/local/lib/python2.7/site-packages/dbfread/field_parser.py", line 75, in parse
    return func(field, data)
  File "/home/chris/frappe-bench/env/local/lib/python2.7/site-packages/dbfread/field_parser.py", line 83, in parseC
    return decode_text(data.rstrip(b'\0 '), self.encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xab in position 16: invalid start byte
```

Any ideas?

**Comment by olemb** [comment]
DBF files typically use older encodings like 'iso-8859-1'. This might work:

    from dbfread import DBF
        for item in DBF('/home/chris/Desktop/ITEM.DBF', encoding='utf-8'):
            print item

**Comment by olemb** [comment]
Sorry, posted to quick. I meant:

    encoding='iso-8859-1'

**Comment by ccfiel** [comment]
@olemb thanks it works!

**Comment by olemb** [comment]
Happy to hear that.

**Comment by AxelBangert** [comment]
... after more than 4 years it worked for me too ... thanks ... very useful :)
Axel

**Comment by Mrabdel-dev** [comment]
thanx its work

**Comment by hado0601** [comment]
tks, useful for me as well

**Comment by rozen666** [comment]
> Sorry, posted to quick. I meant:
> 
> ```
> encoding='iso-8859-1'
> ```

Still Works! Thanks!

**Comment by JuaniFreedoo** [comment]
@olemb thanks, hours and hours looking for a solution

**Comment by squirrelsquirrel78** [comment]
After 8 years, ran into the same issue, still seems to work!
